# Generated by Django 5.0.6 on 2025-04-10 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Papyrus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=100)),
                ('finding_location', models.CharField(max_length=255)),
                ('current_location', models.CharField(max_length=255)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='papyrus.material')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='papyrus.shape')),
            ],
            options={
                'verbose_name_plural': 'papyri',
            },
        ),
        migrations.CreateModel(
            name='PapyrusSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('content', models.TextField()),
                ('parallel', models.BooleanField(default=False)),
                ('flesh', models.BooleanField(default=False)),
                ('concave', models.BooleanField(default=False)),
                ('links', models.JSONField(blank=True, null=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='papyrus.genre')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='papyrus.language')),
                ('papyrus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sides', to='papyrus.papyrus')),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='papyrus.publication')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='papyrus_images/')),
                ('papyrus_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='papyrus.papyrusside')),
            ],
        ),
    ]
