# Generated by Django 5.0.6 on 2025-05-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papyrus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='credit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
