# Generated by Django 5.0.6 on 2025-06-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papyrus', '0003_dimension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papyrusside',
            name='date',
        ),
        migrations.RemoveField(
            model_name='papyrusside',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='papyrusside',
            name='date_start',
        ),
        migrations.AddField(
            model_name='papyrusside',
            name='specific_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='papyrusside',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='papyrusside',
            name='year_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='papyrusside',
            name='year_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='papyrusside',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
