# Generated by Django 5.0.6 on 2025-06-27 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papyrus', '0004_remove_papyrusside_date_remove_papyrusside_date_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='papyrusside',
            old_name='specific_data',
            new_name='specific_date',
        ),
    ]
