# Generated by Django 5.0.6 on 2025-07-11 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papyrus', '0007_currentlocation_findinglocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papyrus',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='papyrus.currentlocation'),
        ),
        migrations.AlterField(
            model_name='papyrus',
            name='finding_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='papyrus.findinglocation'),
        ),
    ]
