# Generated by Django 5.0.6 on 2025-08-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papyrus', '0009_rename_publication_to_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='papyrusside',
            old_name='title',
            new_name='publication',
        ),
    ]
