# Generated by Django 5.2.5 on 2025-09-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papyrus', '0010_rename_title_papyrusside_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('title_nl', models.CharField(max_length=255)),
                ('content_en', models.TextField()),
                ('content_nl', models.TextField()),
                ('menu_bar_order', models.IntegerField(default=0)),
                ('is_list_view', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='papyrusside',
            name='links',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
