# Generated by Django 5.2.5 on 2025-09-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papyrus', '0011_page_remove_papyrusside_links_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
