# Generated by Django 5.2.5 on 2025-09-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papyrus', '0012_page_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_home',
            field=models.BooleanField(default=False, help_text='Set this page as the home page.'),
        ),
    ]
