# Generated by Django 5.2.5 on 2025-09-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papyrus', '0013_page_is_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='papyrusside',
            name='transversa_charta',
            field=models.BooleanField(default=False, verbose_name='Transversa charta'),
        ),
    ]
