# Generated by Django 5.2.5 on 2025-10-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papyrus', '0015_editor_papyrusside_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='papyrusside',
            name='published',
            field=models.BooleanField(default=True, help_text='Visible in list view'),
        ),
    ]
