# Generated by Django 5.2.5 on 2025-10-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papyrus', '0016_papyrusside_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papyrusside',
            name='editor',
        ),
        migrations.AddField(
            model_name='papyrusside',
            name='editors',
            field=models.ManyToManyField(blank=True, to='papyrus.editor'),
        ),
    ]
