# Generated by Django 5.2.5 on 2026-05-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papyrus', '0017_remove_papyrusside_editor_papyrusside_editors'),
    ]

    operations = [
        migrations.AddField(
            model_name='papyrus',
            name='provenance_short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='papyrus',
            name='provenance_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
