# Generated by Django 5.2.5 on 2026-06-19 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papyrus', '0019_papyrusside_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papyrusside',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='papyrus.genre'),
        ),
        migrations.AlterField(
            model_name='papyrusside',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='papyrus.language'),
        ),
    ]
