# Generated by Django 5.2.5 on 2026-06-19 07:50

from django.db import migrations, models


def copy_language_to_languages(apps, schema_editor):
    PapyrusSide = apps.get_model('papyrus', 'PapyrusSide')
    for side in PapyrusSide.objects.exclude(language_id=None):
        side.languages.add(side.language_id)


class Migration(migrations.Migration):

    dependencies = [
        ('papyrus', '0020_alter_papyrusside_genre_alter_papyrusside_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='papyrusside',
            name='languages',
            field=models.ManyToManyField(blank=True, to='papyrus.language'),
        ),
        migrations.RunPython(copy_language_to_languages, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='papyrusside',
            name='language',
        ),
    ]
