# Generated by Django 5.2.5 on 2026-06-19 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papyrus', '0021_remove_papyrusside_language_papyrusside_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='downloads/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='papyrus.page')),
            ],
        ),
    ]
