# Generated by Django 5.2.5 on 2026-06-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papyrus', '0022_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='collection',
            field=models.BooleanField(default=False, help_text='Set this page as a collection page.'),
        ),
    ]
