# Generated by Django 5.2.5 on 2026-06-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papyrus', '0023_page_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='papyrusside',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
